#!/bin/sh

# vim
ln -sf "$PWD/.vimrc" "$HOME/.vimrc"

# zsh
ln -sf "$PWD/zsh/.zshrc" "$HOME/.zshrc"

# tmux
ln -sf "$PWD/tmux/.tmux.conf" "$HOME/.tmux.conf"

sudo apt install build-essential cmake python3.8-dev ripgrep -y

n-install

npm install -g live-server 

# Install Windows Applications
powershell.exe -File ./setup-windows.ps1

