#!/bin/bash

notepath="$HOME/notes"
note="${notepath}/$(date -I).md"
title="${*:1}"

echo $note
if [ ! -f $note ]; then
	touch $note
	printf "## %s\n\n" "$(date -I)" >> $note
fi

printf "\n"

if [ ! -z "$title" ]; then
	printf "### **%s**\n" "$title" >> $note
fi

printf "#### %s\n\n" "$(date +'%T')" >> $note

vim "+normal G$" +startinsert $note

read -p "Commit? [y/N]: " do_commit

if [ "${do_commit,,}" = "y" ]; then
	git -C "$notepath" add .
	git -C "$notepath" commit -m "$title"
	git -C "$notepath" push origin master
fi
